// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Usamos process.env directamente para evitar que Prisma lance un error
    // cuando DATABASE_URL no está definida (ej: en CI durante postinstall)
    url: process.env.DATABASE_URL ?? "postgresql://user:pass@localhost:5432/db",
  },
});
